//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Function
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Function()
        {
            this.User = new HashSet<User>();
            this.Role = new HashSet<Role>();
        }
    
        public int SequenceNo { get; set; }
        public System.Guid ID { get; set; }
        public System.Guid ModuleID { get; set; }
        public byte Sequence { get; set; }
        public byte GroupSequence { get; set; }
        public int BitCode { get; set; }
        public int Dependency { get; set; }
        public string Code { get; set; }
        public string GroupName { get; set; }
        public string SimpleName { get; set; }
        public string DisplayName { get; set; }
        public bool DisplayTree { get; set; }
        public bool DisplayHeader { get; set; }
        public bool IsEnable { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
    
        public virtual Module Module { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Role> Role { get; set; }
    }
}
