#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 01/27/2021 15:54:28
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SampleCode.Models
{
    public interface ISkillRepository : IRepository<Skill>
    {
    }
}
#pragma warning restore 1591
