#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/01/2020 11:32:08
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace SampleCode.Models
{
    public interface IVisualMenuRepository : IRepository<VisualMenu>
    {
    }
}
#pragma warning restore 1591
