#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 01/27/2021 15:54:28
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;

namespace SampleCode.Models
{
    public partial class SkillRepository : Repository<Skill>, ISkillRepository
    {
        public SkillRepository(DbContext _context) : base(_context)
        {
        }
    }
}
#pragma warning restore 1591
