#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 11:34:21
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;

namespace SampleCode.Models
{
    public partial class UserRepository : Repository<User>, IUserRepository
    {
        public UserRepository(DbContext _context) : base(_context)
        {
        }
    }
}
#pragma warning restore 1591
