#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 06/05/2020 19:10:17
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Data.Entity;

namespace SampleCode.Models
{
    public partial class UserChangePassRepository : Repository<UserChangePass>, IUserChangePassRepository
    {
        public UserChangePassRepository(DbContext _context) : base(_context)
        {
        }
    }
}
#pragma warning restore 1591
