#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 10/12/2017 15:20:20
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.Interface;
using SampleCode.ViewModel;
using SampleCode.ViewModel.ListResult;
using SampleCode.ViewModel.SearchModel;
using NLog;
using ResourceLibrary;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Utilities;
using Utilities.Attribute;
using Utilities.Utility;

namespace SampleCode.Controllers
{
    public class FunctionController : BaseController
    {
        readonly ICommonManager _commonManager;
        readonly IFunctionManager _functionManager;

        public FunctionController(
            ICommonManager commonManager,
            IFunctionManager functionManager)
        {
            _commonManager = commonManager;
            _functionManager = functionManager;
            logger = LogManager.GetCurrentClassLogger();
        }

        /// <summary>
        /// 檢查 Code 是否重複
        /// </summary>
        /// <param name="Code"></param>
        /// <param name="Initial"></param>
        /// <returns></returns>
        [WebAuthorize(Code = "FunctionCreate,FunctionEdit")]
        [HttpGet]
        public ActionResult CodeBeUse(string Code, string Initial)
        {
            bool result = false;
            if (Code.Trim().ToLower() != Initial.Trim().ToLower())
            {
                try
                {
                    result = _functionManager.CodeBeUse(Code);
                }
                catch (Exception ex)
                {
                    logger.Error(ex, string.Format(Resource.CheckBeUsedError, Resource.Function, Resource.Code));

                    // 檢查發生錯誤，當作名稱重複，不給儲存。
                    result = true;
                }
            }

            return Json(!result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 首頁
        /// </summary>
        /// <returns></returns>
        [WebAuthorize]
        [HttpGet]
        public ActionResult Index()
        {
            // 初始化查詢物件
            var searchModel = new FunctionSearchModel();
            if (null != UnobtrusiveSession.Session["QueryModel"])
            {
                // 查詢條件存在 session 則取出
                var temp = UnobtrusiveSession.Session["QueryModel"] as FunctionSearchModel;
                if (null != temp)
                {
                    searchModel = temp;
                }
            }
            // 初始化查詢下拉選單
            searchModel.YesNoList = _commonManager.GetYesNoList();

            return View(searchModel);
        }

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        [WebAuthorize(Code = "FunctionIndex")]
        [HttpPost]
        public ActionResult Paging(FunctionSearchModel searchModel)
        {
            // 查詢條件儲存於 session
            UnobtrusiveSession.Session["QueryModel"] = searchModel;
            // 查詢結果物件初始化
            var result = new Paging<FunctionListResult> { total = 0, rows = null };
            // 查詢
            try
            {
                result = _functionManager.Paging(searchModel);
            }
            catch (Exception ex)
            {
                logger.Error(ex, string.Format(Resource.PagingError, Resource.Function));
            }

            return Json(result);
        }

        /// <summary>
        /// ajax 取得特定 controller 裡面的 action list
        /// </summary>
        /// <param name="controllerNmae"></param>
        /// <returns></returns>
        [WebAuthorize(Code = "FunctionCreate,FunctionEdit")]
        [HttpPost]
        public ActionResult GetActionList(string controllerNmae)
        {
            var result = _commonManager.GetActionList(controllerNmae);

            return Json(result);
        }

        /// <summary>
        /// 自動完成群組名稱使用
        /// </summary>
        /// <param name="query"></param>
        /// <returns></returns>
        [WebAuthorize(Code = "FunctionCreate,FunctionEdit")]
        [HttpGet]
        public ActionResult GetGroupName(string query)
        {
            var result = _functionManager.GetGroupName(query);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 取得該模組&群組的最大順序序號
        /// </summary>
        /// <param name="moduleId"></param>
        /// <param name="groupName"></param>
        /// <param name="functionId"></param>
        /// <returns></returns>
        [WebAuthorize(Code = "FunctionCreate,FunctionEdit")]
        [HttpGet]
        public ActionResult GetSequence(Guid moduleId, string groupName, Guid functionId)
        {
            var result = _functionManager.GetSequence(moduleId, groupName, functionId);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// 檢視 Function 頁面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [WebAuthorize]
        [HttpGet]
        public ActionResult Details(Guid? id)
        {
            FunctionViewModel viewModel = null;
            if (id.HasValue && id.Value != Guid.Empty)
            {
                try
                {
                    // 讀取資料
                    viewModel = _functionManager.GetByID(id.Value);
                    if (null == viewModel)
                    {
                        // 查無資料
                        logger.Error(string.Format(Resource.NoData, Resource.Function, id.Value));
                        TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.NoData, Resource.Function, id.Value) }.ToString();
                    }
                }
                catch (Exception ex)
                {
                    // 查詢發生錯誤
                    logger.Error(ex, string.Format(Resource.GetDetailsDataError, Resource.Function, id.Value));
                    TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.GetDetailsDataError, Resource.Function, id.Value) }.ToString();
                }
            }
            else
            {
                // 參數錯誤
                logger.Error(string.Format(Resource.ParamError, Resource.Details));
                TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.ParamError, Resource.Details) }.ToString();
            }
            // 查無資料轉回列表頁
            if (null == viewModel)
            {
                return RedirectToAction("Index");
            }
            // 初始化檢視頁面下拉選單
            setDropDownList(ref viewModel);

            return View(viewModel);
        }

        /// <summary>
        /// 新增 Function 頁面
        /// </summary>
        /// <returns></returns>
        [WebAuthorize]
        [HttpGet]
        public ActionResult Create()
        {
            var viewModel = new FunctionViewModel();
            viewModel.DependencyFunctionList = new List<FunctionViewModel>();
            // 初始化編輯頁面下拉選單
            setDropDownList(ref viewModel);

            return View(viewModel);
        }

        /// <summary>
        /// 新增資料儲存
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [WebAuthorize]
        [HttpPost]
        public ActionResult Create(FunctionViewModel viewModel)
        {
            // 驗證
            if (ModelState.IsValid)
            {
                try
                {
                    viewModel.ID = Guid.NewGuid();
                    _functionManager.Create(viewModel);
                    UnobtrusiveSession.Session["QueryModel"] = null;
                    // 完成
                    TempData["ErrorMsg"] = new JsonMessage { Style = "success", Message = string.Format(Resource.ExecutionCompleted, Resource.Create, Resource.Function) }.ToString();
                    // 轉回列表頁
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // 儲存發生錯誤
                    logger.Error(ex, string.Format(Resource.ExecutionFailedWithID, Resource.Create, Resource.Function, viewModel.ID));
                    TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.ExecutionFailedWithID, Resource.Create, Resource.Function, viewModel.ID) }.ToString();
                }
            }
            // 初始化新增頁面下拉選單
            setDropDownList(ref viewModel);

            return View(viewModel);
        }

        /// <summary>
        /// 修改 Function 頁面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [WebAuthorize]
        [HttpGet]
        public ActionResult Edit(Guid? id)
        {
            FunctionViewModel viewModel = null;
            if (id.HasValue && id.Value != Guid.Empty)
            {
                try
                {
                    // 讀取資料
                    viewModel = _functionManager.GetByID(id.Value);
                    if (null == viewModel)
                    {
                        // 查無資料
                        logger.Error(string.Format(Resource.NoData, Resource.Function, id.Value));
                        TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.NoData, Resource.Function, id.Value) }.ToString();
                    }
                }
                catch (Exception ex)
                {
                    // 查詢發生錯誤
                    logger.Error(ex, string.Format(Resource.GetEditDataError, Resource.Function, id.Value));
                    TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.GetEditDataError, Resource.Function, id.Value) }.ToString();
                }
            }
            else
            {
                // 參數錯誤
                logger.Error(string.Format(Resource.ParamError, Resource.Edit));
                TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.ParamError, Resource.Edit) }.ToString();
            }
            // 查無資料轉回列表頁
            if (null == viewModel)
            {
                return RedirectToAction("Index");
            }
            // 初始化編輯頁面下拉選單
            setDropDownList(ref viewModel);

            return View("Create", viewModel);
        }

        /// <summary>
        /// 編輯資料儲存
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        [WebAuthorize]
        [HttpPost]
        public ActionResult Edit(FunctionViewModel viewModel)
        {
            // 驗證
            if (ModelState.IsValid)
            {
                try
                {
                    _functionManager.Update(viewModel);
                    // 完成
                    TempData["ErrorMsg"] = new JsonMessage { Style = "success", Message = string.Format(Resource.ExecutionCompleted, Resource.Edit, Resource.Function) }.ToString();
                    // 轉回列表頁
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // 儲存發生錯誤
                    logger.Error(ex, string.Format(Resource.ExecutionFailedWithID, Resource.Edit, Resource.Function, viewModel.ID));
                    TempData["ErrorMsg"] = new JsonMessage { Style = "danger", Message = string.Format(Resource.ExecutionFailedWithID, Resource.Edit, Resource.Function, viewModel.ID) }.ToString();
                }
            }
            // 初始化編輯頁面下拉選單
            setDropDownList(ref viewModel);

            return View("Create", viewModel);
        }

        /// <summary>
        /// 刪除機構資料
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [WebAuthorize]
        [HttpPost]
        public ActionResult Delete(List<Guid> id)
        {
            // 預設失敗
            var result = false;
            // id 有值進行刪除作業
            if (id != null && id.Any())
            {
                try
                {
                    // 進行刪除
                    _functionManager.Delete(id);
                    result = true;
                }
                catch (Exception ex)
                {
                    // 刪除失敗
                    logger.Error(ex, string.Format(Resource.ExecutionFailed, Resource.Delete, Resource.Function, id));
                }
            }

            return Json(result);
        }

        /// <summary>
        /// 設定頁面所需要的下拉選單資料
        /// </summary>
        /// <param name="viewModel"></param>
        void setDropDownList(ref FunctionViewModel viewModel)
        {
            viewModel.ActionList = string.IsNullOrWhiteSpace(viewModel.ControllerName) ?
               new SelectList(new List<SelectListItem> { new SelectListItem { Text = string.Format(Resource.PleaseSelect, Resource.ActionName) } }, "Value", "Text") :
               _commonManager.GetActionList(viewModel.ControllerName);
            viewModel.ControllerList = _commonManager.GetControllerList();
            viewModel.ModuleList = _commonManager.GetModuleList();
            if (viewModel.ID != Guid.Empty)
            {
                viewModel.DependencyFunctionList = _functionManager.GetSequence(viewModel.ModuleID, viewModel.GroupName, viewModel.ID).DependencyFunctionList;
            }
        }
    }
}
#pragma warning restore 1591