#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 06/23/2020 15:43:06
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using SampleCode.ViewModel;

namespace SampleCode.Models
{
    public partial class FileAttached
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static FileAttached Convert(FileAttachedViewModel source)
        {
            return source == null ? null : new FileAttached
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                ParentID = source.ParentID,
                TableType = source.TableType ?? string.Empty,
                ItemType = source.ItemType ?? string.Empty,
                FileName = source.FileName ?? string.Empty,
                Description = source.Description ?? string.Empty,
                FileExtension = source.FileExtension ?? string.Empty,
                FilePath = source.FilePath ?? string.Empty,
                FileSize = source.FileSize,
                IsImageFile = source.IsImageFile,
                IsThumbImage = source.IsThumbImage,
                DownloadCount = source.DownloadCount,
                CreateTime = source.CreateTime,
                UpdateTime = DateTime.Now,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static FileAttachedViewModel Convert(FileAttached source)
        {
            return source == null ? null : new FileAttachedViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                ParentID = source.ParentID,
                TableType = source.TableType ?? string.Empty,
                ItemType = source.ItemType ?? string.Empty,
                FileName = source.FileName ?? string.Empty,
                Description = source.Description ?? string.Empty,
                FileExtension = source.FileExtension ?? string.Empty,
                FilePath = source.FilePath ?? string.Empty,
                FileSize = source.FileSize,
                IsImageFile = source.IsImageFile,
                IsThumbImage = source.IsThumbImage,
                DownloadCount = source.DownloadCount,
                CreateTime = source.CreateTime,
                
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator FileAttached(FileAttachedViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator FileAttachedViewModel(FileAttached source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591