#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 11/06/2017 14:27:06
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel;

namespace SampleCode.Models
{
    public partial class FreeFieldSetting
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static FreeFieldSetting Convert(FreeFieldSettingViewModel source)
        {
            return source == null ? null : new FreeFieldSetting
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                TableName = source.TableName ?? string.Empty,
                FieldName = source.FieldName ?? string.Empty,
                DataType = source.DataType,
                Description = source.Description ?? string.Empty,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static FreeFieldSettingViewModel Convert(FreeFieldSetting source)
        {
            return source == null ? null : new FreeFieldSettingViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                TableName = source.TableName ?? string.Empty,
                FieldName = source.FieldName ?? string.Empty,
                DataType = source.DataType,
                Description = source.Description ?? string.Empty,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator FreeFieldSetting(FreeFieldSettingViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator FreeFieldSettingViewModel(FreeFieldSetting source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591