#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 13:01:40
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel;
using ResourceLibrary;
using Utilities;

namespace SampleCode.Models
{
    public partial class Function
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static Function Convert(FunctionViewModel source)
        {
            return source == null ? null : new Function
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                ModuleID = source.ModuleID,
                Sequence = source.Sequence,
                GroupSequence = source.GroupSequence,
                BitCode = source.BitCode,
                Dependency = source.Dependency,
                Code = source.Code ?? string.Empty,
                GroupName = source.GroupName ?? string.Empty,
                SimpleName = source.SimpleName ?? string.Empty,
                DisplayName = source.DisplayName ?? string.Empty,
                DisplayTree = source.DisplayTree,
                DisplayHeader = source.DisplayHeader,
                IsEnable = source.IsEnable,
                ControllerName = source.ControllerName ?? string.Empty,
                ActionName = source.ActionName ?? string.Empty,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static FunctionViewModel Convert(Function source)
        {
            return source == null ? null : new FunctionViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                ModuleID = source.ModuleID,
                Sequence = source.Sequence,
                GroupSequence = source.GroupSequence,
                BitCode = source.BitCode,
                Dependency = source.Dependency,
                Code = source.Code ?? string.Empty,
                GroupName = source.GroupName ?? string.Empty,
                SimpleName = source.SimpleName ?? string.Empty,
                DisplayName = source.DisplayName ?? string.Empty,
                DisplayTree = source.DisplayTree,
                DisplayHeader = source.DisplayHeader,
                IsEnable = source.IsEnable,
                ControllerName = source.ControllerName ?? string.Empty,
                ActionName = source.ActionName ?? string.Empty,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static Auth ConvertToAuth(Function source)
        {
            return source == null ? null : new Auth
            {
                FunctionID = source.ID,
                ControllerName = source.ControllerName,
                ActionName = source.ActionName,
                Code = source.Code,
                ModuleName = LanguageTool.GetResourceValue(source.Module.Name),
                GroupName = LanguageTool.GetResourceValue(source.GroupName),
                SimpleName = LanguageTool.GetResourceValue(source.SimpleName),
                MenuIcon = source.Module.MenuIcon,
                DisplayName = source.DisplayName,
                DisplayTree = source.DisplayTree,
                ModuleSequence = source.Module.Sequence,
                Sequence = source.Sequence,
                GroupSequence = source.GroupSequence,
                BitCode = source.BitCode,
                Dependency = source.Dependency,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator Function(FunctionViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator FunctionViewModel(Function source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator Auth(Function source)
        {
            return ConvertToAuth(source);
        }
    }
}
#pragma warning restore 1591