#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 13:01:40
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel;

namespace SampleCode.Models
{
    public partial class Module
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static Module Convert(ModuleViewModel source)
        {
            return source == null ? null : new Module
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                Sequence = source.Sequence,
                Name = source.Name ?? string.Empty,
                MenuIcon = source.MenuIcon ?? string.Empty,
                IsEnable = source.IsEnable,
                MenuDisplay = source.MenuDisplay,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static ModuleViewModel Convert(Module source)
        {
            return source == null ? null : new ModuleViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                Sequence = source.Sequence,
                Name = source.Name ?? string.Empty,
                MenuIcon = source.MenuIcon ?? string.Empty,
                IsEnable = source.IsEnable,
                MenuDisplay = source.MenuDisplay,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator Module(ModuleViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator ModuleViewModel(Module source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591