#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 01/27/2021 15:54:38
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel;

namespace SampleCode.Models
{
    public partial class Skill
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static Skill Convert(SkillViewModel source)
        {
            return source == null ? null : new Skill
            {
                rowId = source.rowId,
                name = source.name ?? string.Empty,
                isSelected = source.isSelected,
                type = source.type ?? string.Empty,
                abc = source.abc ?? string.Empty,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static SkillViewModel Convert(Skill source)
        {
            return source == null ? null : new SkillViewModel
            {
                rowId = source.rowId,
                name = source.name ?? string.Empty,
                isSelected = source.isSelected,
                type = source.type ?? string.Empty,
                abc = source.abc ?? string.Empty,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator Skill(SkillViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator SkillViewModel(Skill source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591