#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/26/2019 09:29:52
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel;

namespace SampleCode.Models
{
    public partial class SystemOption
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static SystemOption Convert(SystemOptionViewModel source)
        {
            return source == null ? null : new SystemOption
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                Category = source.Category ?? string.Empty,
                OptionKey = source.OptionKey ?? string.Empty,
                OptionValue = source.OptionValue ?? string.Empty,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static SystemOptionViewModel Convert(SystemOption source)
        {
            return source == null ? null : new SystemOptionViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                Category = source.Category ?? string.Empty,
                OptionKey = source.OptionKey ?? string.Empty,
                OptionValue = source.OptionValue ?? string.Empty,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator SystemOption(SystemOptionViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator SystemOptionViewModel(SystemOption source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591