#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/26/2019 09:29:52
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel;

namespace SampleCode.Models
{
    public partial class SystemConfig
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static SystemConfig Convert(SystemConfigViewModel source)
        {
            return source == null ? null : new SystemConfig
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                ConfigKey = source.ConfigKey ?? string.Empty,
                ConfigValue = source.ConfigValue ?? string.Empty,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static SystemConfigViewModel Convert(SystemConfig source)
        {
            return source == null ? null : new SystemConfigViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                ConfigKey = source.ConfigKey ?? string.Empty,
                ConfigValue = source.ConfigValue ?? string.Empty,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator SystemConfig(SystemConfigViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator SystemConfigViewModel(SystemConfig source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591