#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 13:01:40
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel;
using SampleCode.ViewModel.ListResult;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace SampleCode.Models
{
    public partial class UserProfile
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static UserProfile Convert(UserProfileViewModel source)
        {
            var listOption = JsonConvert.SerializeObject(source.ListOption);

            return source == null ? null : new UserProfile
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                UserID = source.UserID,
                Code = source.Code ?? string.Empty,
                ListOption = string.IsNullOrEmpty(listOption) ? "{}" : listOption,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static UserProfileViewModel Convert(UserProfile source)
        {
            var listOption = new List<ListOption>();
            if (null != source && !string.IsNullOrEmpty(source.ListOption))
            {
                try
                {
                    listOption = JsonConvert.DeserializeObject<List<ListOption>>(source.ListOption);
                }
                catch
                {
                }
            }

            return source == null ? null : new UserProfileViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                UserID = source.UserID,
                Code = source.Code ?? string.Empty,
                ListOption = listOption,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator UserProfile(UserProfileViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator UserProfileViewModel(UserProfile source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591