#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 10/24/2017 11:43:17
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;
using SampleCode.ViewModel;
using SampleCode.ViewModel.Struct;

namespace SampleCode.Models
{
    public partial class User
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static User Convert(UserViewModel source)
        {
            return source == null ? null : new User
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                Name = source.Name ?? string.Empty,
                Account = source.Account ?? string.Empty,
                Password = source.Password ?? string.Empty,
                Email = source.Email ?? string.Empty,
                ContactTel = source.ContactTel ?? string.Empty,
                IsEnable = source.IsEnable,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
                LoginTime = source.LoginTime,
                ChangePassTime = source.ChangePassTime,
                PhotoPath = source.PhotoPath ?? string.Empty,
                IsToken = false,
                HashToken = source.HashToken ?? string.Empty,
                TokenData = string.Empty,
                FreeFields = null == source.FreeFields ? "{}" : source.FreeFields.ToString(),
                DefaultIndex = source.DefaultIndex,
                DepartmentID = source.DepartmentID,
                DepartmentIDs = JsonConvert.SerializeObject(source.DepartmentIDs),
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static UserViewModel Convert(User source)
        {
            var freeFields = null != source && !string.IsNullOrEmpty(source.FreeFields) ?
                new TemplateFields(source.FreeFields) :
                new TemplateFields();

            return source == null ? null : new UserViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                Name = source.Name ?? string.Empty,
                Account = source.Account ?? string.Empty,
                Password = source.Password ?? string.Empty,
                Email = source.Email ?? string.Empty,
                ContactTel = source.ContactTel ?? string.Empty,
                IsEnable = source.IsEnable,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
                LoginTime = source.LoginTime,
                ChangePassTime = source.ChangePassTime,
                PhotoPath = source.PhotoPath ?? string.Empty,
                HashToken = source.HashToken ?? string.Empty,
                FreeFields = freeFields,
                DefaultIndex = source.DefaultIndex,
                DepartmentID = source.DepartmentID,
                DepartmentIDs = JsonConvert.DeserializeObject<List<Guid>>(source.DepartmentIDs),
                RoleID = source.Role.Select(x => x.ID).ToList()
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator User(UserViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator UserViewModel(User source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591