#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 06/23/2020 15:43:06
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel;

namespace SampleCode.Models
{
    public partial class UserChangePass
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static UserChangePass Convert(UserChangePassViewModel source)
        {
            return source == null ? null : new UserChangePass
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                UserID = source.UserID,
                Password = source.Password ?? string.Empty,
                ChangeTime = source.ChangeTime,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static UserChangePassViewModel Convert(UserChangePass source)
        {
            return source == null ? null : new UserChangePassViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                UserID = source.UserID,
                Password = source.Password ?? string.Empty,
                ChangeTime = source.ChangeTime,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator UserChangePass(UserChangePassViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator UserChangePassViewModel(UserChangePass source)
        {
            return Convert(source);
        }
    }
}
#pragma warning restore 1591