#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/01/2020 11:32:13
//       Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.Models.Public;
using SampleCode.ViewModel;

namespace SampleCode.Models
{
    public partial class VisualMenu
    {
        /// <summary>
        /// 將 ViewModel 轉換為 Model 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static VisualMenu Convert(VisualMenuViewModel source)
        {
            return source == null ? null : new VisualMenu
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                ParentID = source.ParentID,
                Sequence = source.Sequence,
                MenuLevel = source.MenuLevel,
                MenuCode = source.MenuCode ?? string.Empty,
                MenuName = source.MenuName ?? string.Empty,
                Layout = source.Layout ?? string.Empty,
                IconPath = source.IconPath ?? string.Empty,
                HeaderPath = source.HeaderPath ?? string.Empty,
                ViewCount = source.ViewCount,
                Controller = source.Controller ?? string.Empty,
                Action = source.Action ?? string.Empty,
                Parameter = source.Parameter ?? string.Empty,
                ExternalUrl = source.ExternalUrl ?? string.Empty,
                IsInlinePage = source.IsInlinePage,
                IsShowFooter = source.IsShowFooter,
                IsEnable = source.IsEnable,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 ViewModel 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static VisualMenuViewModel Convert(VisualMenu source)
        {
            return source == null ? null : new VisualMenuViewModel
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                ParentID = source.ParentID,
                Sequence = source.Sequence,
                MenuLevel = source.MenuLevel,
                MenuCode = source.MenuCode ?? string.Empty,
                MenuName = source.MenuName ?? string.Empty,
                Layout = source.Layout ?? string.Empty,
                IconPath = source.IconPath ?? string.Empty,
                HeaderPath = source.HeaderPath ?? string.Empty,
                ViewCount = source.ViewCount,
                Controller = source.Controller ?? string.Empty,
                Action = source.Action ?? string.Empty,
                Parameter = source.Parameter ?? string.Empty,
                ExternalUrl = source.ExternalUrl ?? string.Empty,
                IsInlinePage = source.IsInlinePage,
                IsShowFooter = source.IsShowFooter,
                IsEnable = source.IsEnable,
                CreateUser = source.CreateUser ?? string.Empty,
                CreateTime = source.CreateTime,
                UpdateUser = source.UpdateUser ?? string.Empty,
                UpdateTime = source.UpdateTime,
            };
        }

        /// <summary>
        /// 將 Model 轉換為 Menu 物件
        /// </summary>
        /// <param name="source"></param>
        /// <returns></returns>
        public static Menu ConvertHome(VisualMenu source)
        {
            return source == null ? null : new Menu
            {
                SequenceNo = source.SequenceNo,
                ID = source.ID,
                ParentID = source.ParentID,
                Sequence = source.Sequence,
                MenuLevel = source.MenuLevel,
                MenuCode = source.MenuCode ?? string.Empty,
                MenuName = source.MenuName ?? string.Empty,
                Layout = source.Layout ?? string.Empty,
                IconPath = source.IconPath ?? string.Empty,
                HeaderPath = source.HeaderPath ?? string.Empty,
                ViewCount = source.ViewCount,
                Controller = source.Controller ?? string.Empty,
                Action = source.Action ?? string.Empty,
                Parameter = source.Parameter ?? string.Empty,
                ExternalUrl = source.ExternalUrl ?? string.Empty,
                IsInlinePage = source.IsInlinePage,
                IsShowFooter = source.IsShowFooter,
                IsEnable = source.IsEnable,
            };
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator VisualMenu(VisualMenuViewModel source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator VisualMenuViewModel(VisualMenu source)
        {
            return Convert(source);
        }

        /// <summary>
        /// 轉換運算子
        /// </summary>
        /// <param name="source"></param>
        public static explicit operator Menu(VisualMenu source)
        {
            return ConvertHome(source);
        }
    }
}
#pragma warning restore 1591