#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/26/2019 09:30:43
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Utilities.Extensions;
using SampleCode.Interface;
using SampleCode.Models;
using SampleCode.ViewModel;
using SampleCode.ViewModel.ListResult;
using SampleCode.ViewModel.SearchModel;
using ResourceLibrary;
using System.Web.Mvc;
using SampleCode;

namespace SampleCode.Manager
{
    public class SystemOptionManager : ISystemOptionManager
    {
        readonly ISystemOptionRepository _systemOptionRepository;

        public SystemOptionManager(ISystemOptionRepository systemOptionRepository)
        {
            _systemOptionRepository = systemOptionRepository;
        }

        /// <summary>
        /// 建立 SystemOption
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public void Create(SystemOptionViewModel entity)
        {
            var item = (SystemOption)entity;

            using (var transaction = _systemOptionRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    _systemOptionRepository.Create(item);
                    transaction.Commit();
                    //更新快取資料
                    Global.UpdateEntity("Option", item);
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// 根據 id 刪除 SystemOption
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public void Delete(List<Guid> id)
        {
            using (var transaction = _systemOptionRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    var itemSet = _systemOptionRepository.Where(x => id.Contains(x.ID)).ToList();
                    if (itemSet.Any())
                    {
                        foreach (var item in itemSet)
                        {
                            _systemOptionRepository.Delete(item);
                        }
                    }
                    transaction.Commit();
                    //更新快取資料
                    Global.UpdateEntity("Option", null, id);
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// 根據 id 取得 SystemOption
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public SystemOptionViewModel GetByID(Guid id)
        {
            var item = _systemOptionRepository.GetByID(id);
            var result = (SystemOptionViewModel)item;

            return result;
        }

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        public Paging<SystemOptionListResult> Paging(SystemOptionSearchModel searchModel)
        {
            // 預設集合
            var temp = _systemOptionRepository.GetAll();

            // 將 DB 資料轉換為列表頁呈現資料
            var tempResult = from x in temp
                             select new SystemOptionListResult
                             {
                                 SequenceNo = x.SequenceNo,
                                 ID = x.ID,
                                 Category = x.Category,
                                 OptionKey = x.OptionKey,
                                 OptionValue = x.OptionValue,
                                 UpdateUser = x.UpdateUser,
                                 UpdateTime = x.UpdateTime,
                             };

            // 如有篩選條件，進行篩選
            if (!string.IsNullOrWhiteSpace(searchModel.Search))
            {
                var search = searchModel.Search.ToLower();
                tempResult = tempResult.Where(x =>
                    x.Category.Contains(search) ||
                    x.OptionKey.Contains(search) ||
                    x.OptionValue.Contains(search) ||
                    x.UpdateUser.Contains(search) ||
                    false);
            }

            // 進行分頁處理
            var result = new Paging<SystemOptionListResult>();
            result.total = tempResult.Count();
            result.rows = tempResult
                .OrderBy(searchModel.Sort, searchModel.Order)
                .Skip(searchModel.Offset)
                .Take(searchModel.Limit)
                .ToList();

            return result;
        }

        /// <summary>
        /// 更新 SystemOption
        /// </summary>
        /// <param name="entity"></param>
        public void Update(SystemOptionViewModel entity)
        {
            using (var transaction = _systemOptionRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    var source = _systemOptionRepository.GetByID(entity.ID);
                    source.Category = entity.Category ?? string.Empty;
                    source.OptionKey = entity.OptionKey ?? string.Empty;
                    source.OptionValue = entity.OptionValue ?? string.Empty;
                    source.UpdateUser = entity.UpdateUser ?? string.Empty;
                    source.UpdateTime = entity.UpdateTime;

                    _systemOptionRepository.Update(source);
                    transaction.Commit();
                    //更新快取資料
                    Global.UpdateEntity("Option", source);
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// 取得標題的下拉選單
        /// </summary>
        /// <returns></returns>
        public SelectList GetCardTitleList()
        {
            var list = new List<SelectListItem>();
            var options = _systemOptionRepository.GetAll().Where(x => x.Category == "CardTitle").ToList();
            if (options.Count > 0)
                list.AddRange(options.Select(x => new SelectListItem { Value = x.ID.ToString(), Text = x.OptionValue }));
            var result = new SelectList(list, "Value", "Text");

            return result;
        }

        /// <summary>
        /// 取得系統選項
        /// </summary>
        /// <returns></returns>
        public List<SystemOptionViewModel> GetOptions(string category)
        {

            var result = _systemOptionRepository.GetAll().Where(x => x.Category == category).ToList().ConvertAll(e => (SystemOptionViewModel)e);

            return result;
        }

        /// <summary>
        /// 取得新增欄位勾選項目
        /// </summary>
        /// <returns></returns>
        public List<string> GetAddCloumns()
        {

            var result = _systemOptionRepository.GetAll().Where(x => x.Category == "AddColumn").Select(x => x.OptionValue).ToList();

            return result;
        }
    }
}
#pragma warning restore 1591