#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/26/2019 09:30:43
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using Utilities.Extensions;
using SampleCode.Interface;
using SampleCode.Models;
using SampleCode.ViewModel;
using SampleCode.ViewModel.ListResult;
using SampleCode.ViewModel.SearchModel;
using ResourceLibrary;
using SampleCode;

namespace SampleCode.Manager
{
    public class SystemConfigManager : ISystemConfigManager
    {
        readonly ISystemConfigRepository _systemConfigRepository;

        public SystemConfigManager(ISystemConfigRepository systemConfigRepository)
        {
            _systemConfigRepository = systemConfigRepository;
        }

        /// <summary>
        /// 建立 SystemConfig
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        public void Create(SystemConfigViewModel entity)
        {
            var item = (SystemConfig)entity;

            using (var transaction = _systemConfigRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    _systemConfigRepository.Create(item);
                    transaction.Commit();
                    //更新快取資料
                    Global.UpdateEntity("Config", item);
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// 根據 id 刪除 SystemConfig
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public void Delete(List<Guid> id)
        {
            using (var transaction = _systemConfigRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    var itemSet = _systemConfigRepository.Where(x => id.Contains(x.ID)).ToList();
                    if (itemSet.Any())
                    {
                        foreach (var item in itemSet)
                        {
                            _systemConfigRepository.Delete(item);
                        }
                    }
                    transaction.Commit();
                    //更新快取資料
                    Global.UpdateEntity("Config", null, id);
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }

        /// <summary>
        /// 根據 id 取得 SystemConfig
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public SystemConfigViewModel GetByID(Guid id)
        {
            var item = _systemConfigRepository.GetByID(id);
            var result = (SystemConfigViewModel)item;

            return result;
        }

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        public Paging<SystemConfigListResult> Paging(SystemConfigSearchModel searchModel)
        {
            // 預設集合
            var temp = _systemConfigRepository.GetAll();

            // 將 DB 資料轉換為列表頁呈現資料
            var tempResult = from x in temp
                             select new SystemConfigListResult
                             {
                                 SequenceNo = x.SequenceNo,
                                 ID = x.ID,
                                 ConfigKey = x.ConfigKey,
                                 ConfigValue = x.ConfigValue,
                                 UpdateUser = x.UpdateUser,
                                 UpdateTime = x.UpdateTime,
                             };

            // 如有篩選條件，進行篩選
            if (!string.IsNullOrWhiteSpace(searchModel.Search))
            {
                var search = searchModel.Search.ToLower();
                tempResult = tempResult.Where(x =>
                    x.ConfigKey.Contains(search) ||
                    x.ConfigValue.Contains(search) ||
                    x.UpdateUser.Contains(search) ||
                    false);
            }

            // 進行分頁處理
            var result = new Paging<SystemConfigListResult>();
            result.total = tempResult.Count();
            result.rows = tempResult
                .OrderBy(searchModel.Sort, searchModel.Order)
                .Skip(searchModel.Offset)
                .Take(searchModel.Limit)
                .ToList();

            return result;
        }

        /// <summary>
        /// 更新 SystemConfig
        /// </summary>
        /// <param name="entity"></param>
        public void Update(SystemConfigViewModel entity)
        {
            using (var transaction = _systemConfigRepository.dbContext.Database.BeginTransaction())
            {
                try
                {
                    var source = _systemConfigRepository.GetByID(entity.ID);
                    source.ConfigKey = entity.ConfigKey ?? string.Empty;
                    source.ConfigValue = entity.ConfigValue ?? string.Empty;
                    source.UpdateUser = entity.UpdateUser ?? string.Empty;
                    source.UpdateTime = entity.UpdateTime;

                    _systemConfigRepository.Update(source);
                    transaction.Commit();
                    //更新快取資料
                    Global.UpdateEntity("Config", source);
                }
                catch
                {
                    transaction.Rollback();
                    throw;
                }
            }
        }
    }
}
#pragma warning restore 1591