#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 11/06/2017 14:33:31
//	   Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel.Struct;
using ResourceLibrary;
using System;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using System.Web;

namespace SampleCode.ViewModel
{
    public class DepartmentBaseModel
    {
        public DepartmentBaseModel()
        {
            IsEnable = true;
        }

        #region == DB Fields ==

        /// <summary>
        /// SequenceNo
        /// </summary>
        public int SequenceNo { get; set; }

        /// <summary>
        /// ID
        /// </summary>
        public Guid ID { get; set; }

        /// <summary>
        /// Sequence
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Sequence", ResourceType = typeof(Resource))]
        [Range(byte.MinValue, byte.MaxValue, ErrorMessageResourceName = "RangeError", ErrorMessageResourceType = typeof(Resource))]
        public byte Sequence { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(50, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Name", ResourceType = typeof(Resource))]
        public string Name { get; set; }

        /// <summary>
        /// Abbreviate
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(10, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Name", ResourceType = typeof(Resource))]
        public string Abbreviate { get; set; }

        /// <summary>
        /// DepartmentLevel
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "DepartmentLevel", ResourceType = typeof(Resource))]
        [Range(byte.MinValue, byte.MaxValue, ErrorMessageResourceName = "RangeError", ErrorMessageResourceType = typeof(Resource))]
        public byte DepartmentLevel { get; set; }

        /// <summary>
        /// ContactTel
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(20, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "ContactTel", ResourceType = typeof(Resource))]
        public string ContactTel { get; set; }

        /// <summary>
        /// ContactFax
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(20, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "ContactFax", ResourceType = typeof(Resource))]
        public string ContactFax { get; set; }

        /// <summary>
        /// Address
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(64, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Address", ResourceType = typeof(Resource))]
        public string Address { get; set; }

        /// <summary>
        /// WebSiteUrl
        /// </summary>
        [StringLength(128, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "WebSiteUrl", ResourceType = typeof(Resource))]
        public string WebSiteUrl { get; set; }

        /// <summary>
        /// ImagePath
        /// </summary>
        [StringLength(128, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "ImagePath", ResourceType = typeof(Resource))]
        public string ImagePath { get; set; }

        /// <summary>
        /// ImageAlt
        /// </summary>
        [StringLength(50, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "ImageAlt", ResourceType = typeof(Resource))]
        public string ImageAlt { get; set; }

        /// <summary>
        /// ImageWidth
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "ImageWidth", ResourceType = typeof(Resource))]
        public short ImageWidth { get; set; }

        /// <summary>
        /// ImageHeight
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "ImageHeight", ResourceType = typeof(Resource))]
        public short ImageHeight { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [DataType(DataType.MultilineText)]
        [StringLength(2000, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Description", ResourceType = typeof(Resource))]
        public string Description { get; set; }

        /// <summary>
        /// IsEnable
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "IsEnable", ResourceType = typeof(Resource))]
        public bool IsEnable { get; set; }

        /// <summary>
        /// CreateUser
        /// </summary>
        [StringLength(50, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "CreateUser", ResourceType = typeof(Resource))]
        public string CreateUser { get; set; }

        /// <summary>
        /// CreateTime
        /// </summary>
        [Display(Name = "CreateTime", ResourceType = typeof(Resource))]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// UpdateUser
        /// </summary>
        [StringLength(50, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "UpdateUser", ResourceType = typeof(Resource))]
        public string UpdateUser { get; set; }

        /// <summary>
        /// UpdateTime
        /// </summary>
        [Display(Name = "UpdateTime", ResourceType = typeof(Resource))]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime UpdateTime { get; set; }

        /// <summary>
        /// FreeFields
        /// </summary>
        public TemplateFields FreeFields { get; set; }

        /// <summary>
        /// HeadID
        /// </summary>
        [Display(Name = "DepartmentHead", ResourceType = typeof(Resource))]
        public Nullable<Guid> HeadID { get; set; }

        /// <summary>
        /// ParentID
        /// </summary>
        [Display(Name = "DepartmentParent", ResourceType = typeof(Resource))]
        public Nullable<Guid> ParentID { get; set; }

        #endregion == DB Fields ==
    }

    public class DepartmentViewModel : DepartmentBaseModel
    {
        #region == View Fields ==

        public SelectList HeadList { get; set; }

        public SelectList ParentList { get; set; }

        /// <summary>
        /// 圖示上傳物件
        /// </summary>
        [Display(Name = "UploadImage", ResourceType = typeof(Resource))]
        public HttpPostedFileBase ImageUpload { get; set; }

        #endregion == View Fields ==
    }
}
#pragma warning restore 1591