#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 11/06/2017 14:33:31
//	   Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ResourceLibrary;
using System;
using System.ComponentModel.DataAnnotations;

namespace SampleCode.ViewModel
{
    public class FreeFieldSettingBaseModel
    {
        public FreeFieldSettingBaseModel()
        {
        }

        #region == DB Fields ==

        /// <summary>
        /// SequenceNo
        /// </summary>
        public int SequenceNo { get; set; }

        /// <summary>
        /// ID
        /// </summary>
        public Guid ID { get; set; }

        /// <summary>
        /// TableName
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(100, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "TableName", ResourceType = typeof(Resource))]
        public string TableName { get; set; }

        /// <summary>
        /// FieldName
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(100, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "FieldName", ResourceType = typeof(Resource))]
        public string FieldName { get; set; }

        /// <summary>
        /// DataType
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "DataType", ResourceType = typeof(Resource))]
        public bool DataType { get; set; }

        /// <summary>
        /// Description
        /// </summary>
        [DataType(System.ComponentModel.DataAnnotations.DataType.MultilineText)]
        [StringLength(256, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Description", ResourceType = typeof(Resource))]
        public string Description { get; set; }

        #endregion == DB Fields ==
    }

    public class FreeFieldSettingViewModel : FreeFieldSettingBaseModel
    {
        #region == View Fields ==

        #endregion == View Fields ==
    }
}
#pragma warning restore 1591