#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 13:00:22
//	   Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel.Struct;
using ResourceLibrary;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;
using Utilities;

namespace SampleCode.ViewModel
{
    public class UserBaseModel
    {
        public UserBaseModel()
        {
            IsEnable = true;
        }

        #region == DB Fields ==

        /// <summary>
        /// SequenceNo
        /// </summary>
        public int SequenceNo { get; set; }

        /// <summary>
        /// ID
        /// </summary>
        public Guid ID { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(50, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "UserName", ResourceType = typeof(Resource))]
        public string Name { get; set; }

        /// <summary>
        /// Account
        /// </summary>
        [Remote("AccountBeUse", "User", AdditionalFields = "Initial", ErrorMessageResourceName = "BeUsedError", ErrorMessageResourceType = typeof(Resource))]
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(256, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Account", ResourceType = typeof(Resource))]
        public string Account { get; set; }

        /// <summary>
        /// Password
        /// </summary>
        [DataType(DataType.Password)]
        [StringLength(128, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Password", ResourceType = typeof(Resource))]
        [RegularExpression("^(?=.*[A-Z])(?=.*[!@#$&\\-_*])(?=.*[0-9])(?=.*[a-z]).{8,12}$", ErrorMessageResourceName = "PasswordError", ErrorMessageResourceType = typeof(Resource))]
        public string Password { get; set; }

        /// <summary>
        /// Email
        /// </summary>
        [DataType(DataType.EmailAddress, ErrorMessageResourceName = "EmailError", ErrorMessageResourceType = typeof(Resource))]
        [EmailAddress(ErrorMessageResourceName = "EmailError", ErrorMessageResourceType = typeof(Resource))]
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(256, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Email", ResourceType = typeof(Resource))]
        public string Email { get; set; }

        /// <summary>
        /// ContactTel
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(20, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "ContactTel", ResourceType = typeof(Resource))]
        public string ContactTel { get; set; }

        /// <summary>
        /// IsEnable
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "IsEnable", ResourceType = typeof(Resource))]
        public bool IsEnable { get; set; }

        /// <summary>
        /// CreateUser
        /// </summary>
        [StringLength(50, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "CreateUser", ResourceType = typeof(Resource))]
        public string CreateUser { get; set; }

        /// <summary>
        /// CreateTime
        /// </summary>
        [Display(Name = "CreateTime", ResourceType = typeof(Resource))]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// UpdateUser
        /// </summary>
        [StringLength(50, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "UpdateUser", ResourceType = typeof(Resource))]
        public string UpdateUser { get; set; }

        /// <summary>
        /// UpdateTime
        /// </summary>
        [Display(Name = "UpdateTime", ResourceType = typeof(Resource))]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime UpdateTime { get; set; }

        /// <summary>
        /// LoginTime
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "LoginTime", ResourceType = typeof(Resource))]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime LoginTime { get; set; }

        /// <summary>
        /// ChnagePassTime
        /// </summary>
        [Display(Name = "ChangePassTime", ResourceType = typeof(Resource))]
        [DisplayFormat(DataFormatString = "{0:yyyy/MM/dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime ChangePassTime { get; set; }

        /// <summary>
        /// PhotoPath
        /// </summary>
        [StringLength(256, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "PhotoPath", ResourceType = typeof(Resource))]
        public string PhotoPath { get; set; }

        /// <summary>
        /// HashToken
        /// </summary>
        [StringLength(256, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "HashToken", ResourceType = typeof(Resource))]
        public string HashToken { get; set; }

        /// <summary>
        /// FreeFields
        /// </summary>
        public TemplateFields FreeFields { get; set; }

        /// <summary>
        /// DefaultIndex
        /// </summary>
        [Display(Name = "DefaultIndex", ResourceType = typeof(Resource))]
        public Nullable<Guid> DefaultIndex { get; set; }

        /// <summary>
        /// DepartmentID
        /// </summary>
        //[Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Department", ResourceType = typeof(Resource))]
        public Nullable<Guid> DepartmentID { get; set; }

        /// <summary>
        /// DepartmentIDs
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Department", ResourceType = typeof(Resource))]
        public List<Guid> DepartmentIDs { get; set; }

        #endregion == DB Fields ==
    }

    public class UserViewModel : UserBaseModel
    {
        #region == View Fields ==

        /// <summary>
        /// 使用者擁有的功能清單
        /// </summary>
        public List<Auth> Auth { get; set; }

        /// <summary>
        /// 功能下拉
        /// </summary>
        public SelectList FunctionList { get; set; }

        /// <summary>
        /// 圖示上傳物件
        /// </summary>
        [Display(Name = "UploadPhoto", ResourceType = typeof(Resource))]
        public HttpPostedFileBase PhotoUpload { get; set; }

        /// <summary>
        /// 使用者擁有的角色
        /// </summary>
        [Display(Name = "Role", ResourceType = typeof(Resource))]
        public List<Guid> RoleID { get; set; }

        /// <summary>
        /// 角色下拉
        /// </summary>
        public SelectList RoleList { get; set; }

        /// <summary>
        /// 部門下拉
        /// </summary>
        public SelectList DepartmentList { get; set; }

        /// <summary>
        /// 跑馬燈
        /// </summary>
        public List<string> Marquee { get; set; }

        #endregion == View Fields ==
    }
}
#pragma warning restore 1591