#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 13:00:22
//	   Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel.ListResult;
using ResourceLibrary;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace SampleCode.ViewModel
{
    public class UserProfileBaseModel
    {
        public UserProfileBaseModel()
        {
        }

        #region == DB Fields ==

        /// <summary>
        /// SequenceNo
        /// </summary>
        public int SequenceNo { get; set; }

        /// <summary>
        /// ID
        /// </summary>
        public Guid ID { get; set; }

        /// <summary>
        /// UserID
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "UserName", ResourceType = typeof(Resource))]
        public Guid UserID { get; set; }

        /// <summary>
        /// Code
        /// </summary>
        [Required(ErrorMessageResourceName = "RequiredError", ErrorMessageResourceType = typeof(Resource))]
        [StringLength(50, ErrorMessageResourceName = "StringLengthError", ErrorMessageResourceType = typeof(Resource))]
        [Display(Name = "Code", ResourceType = typeof(Resource))]
        [Remote("CodeBeUse", "UserProfile", AdditionalFields = "Initial", ErrorMessageResourceName = "BeUsedError", ErrorMessageResourceType = typeof(Resource))]
        public string Code { get; set; }

        /// <summary>
        /// ListOption
        /// </summary>
        [Display(Name = "ListOption", ResourceType = typeof(Resource))]
        public List<ListOption> ListOption { get; set; }

        #endregion == DB Fields ==
    }

    public class UserProfileViewModel : UserProfileBaseModel
    {
        #region == View Fields ==

        public SelectList UserList { get; set; }

        #endregion == View Fields ==
    }
}
#pragma warning restore 1591