#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 11/06/2017 14:27:32
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using SampleCode.ViewModel;
using SampleCode.ViewModel.ListResult;
using SampleCode.ViewModel.SearchModel;

namespace SampleCode.Interface
{
    public interface IFreeFieldSettingManager : IManager
    {
        /// <summary>
        /// 建立 FreeFieldSetting
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(FreeFieldSettingViewModel entity);

        /// <summary>
        /// 根據 id 刪除 FreeFieldSetting
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 根據 id 取得 FreeFieldSetting
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        FreeFieldSettingViewModel GetByID(Guid id);

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<FreeFieldSettingListResult> Paging(FreeFieldSettingSearchModel searchModel);

        /// <summary>
        /// 更新 FreeFieldSetting
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(FreeFieldSettingViewModel entity);
    }
}
#pragma warning restore 1591