#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 01/27/2021 15:54:10
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using SampleCode.ViewModel;
using SampleCode.ViewModel.ListResult;
using SampleCode.ViewModel.SearchModel;

namespace SampleCode.Interface
{
    public interface IOperateRecordManager : IManager
    {
        /// <summary>
        /// 建立 OperateRecord
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(OperateRecordViewModel entity);

        /// <summary>
        /// 根據 id 刪除 OperateRecord
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 根據 id 取得 OperateRecord
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        OperateRecordViewModel GetByID(Guid id);

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<OperateRecordListResult> Paging(OperateRecordSearchModel searchModel);

        /// <summary>
        /// 更新 OperateRecord
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(OperateRecordViewModel entity);
    }
}
#pragma warning restore 1591