#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/26/2019 09:31:06
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using SampleCode.ViewModel;
using SampleCode.ViewModel.ListResult;
using SampleCode.ViewModel.SearchModel;

namespace SampleCode.Interface
{
    public interface ISystemOptionManager : IManager
    {
        /// <summary>
        /// 建立 SystemOption
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(SystemOptionViewModel entity);

        /// <summary>
        /// 根據 id 刪除 SystemOption
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 根據 id 取得 SystemOption
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        SystemOptionViewModel GetByID(Guid id);

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<SystemOptionListResult> Paging(SystemOptionSearchModel searchModel);

        /// <summary>
        /// 更新 SystemOption
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(SystemOptionViewModel entity);

        /// <summary>
        /// 取得標題的下拉選單
        /// </summary>
        /// <returns></returns>
        SelectList GetCardTitleList();

        /// <summary>
        /// 取得系統選項
        /// </summary>
        /// <returns></returns>
        List<SystemOptionViewModel> GetOptions(string category);

        /// <summary>
        /// 取得新增欄位勾選項目
        /// </summary>
        /// <returns></returns>
        List<string> GetAddCloumns();
    }
}
#pragma warning restore 1591