#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 13:04:04
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel;
using SampleCode.ViewModel.ListResult;
using SampleCode.ViewModel.SearchModel;
using System;
using System.Collections.Generic;

namespace SampleCode.Interface
{
    public interface IUserProfileManager : IManager
    {
        /// <summary>
        /// 檢查 Code 是否已經被使用
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        bool CodeBeUse(string code);

        /// <summary>
        /// 建立 UserProfile
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(UserProfileViewModel entity);

        /// <summary>
        /// 根據 id 刪除 UserProfile
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 根據 id 取得 UserProfile
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        UserProfileViewModel GetByID(Guid id);

        /// <summary>
        /// 根據 id 取得 UserProfile
        /// </summary>
        /// <param name="userId"></param>
        /// <param name="functionName"></param>
        /// <returns></returns>
        UserProfileViewModel GetByUserIDAndFunction(Guid userId, string functionName);

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<UserProfileListResult> Paging(UserProfileSearchModel searchModel);

        /// <summary>
        /// Create/Edit profile
        /// </summary>
        /// <param name="entity"></param>
        void Save(UserProfileViewModel entity);

        /// <summary>
        /// 更新 UserProfile
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(UserProfileViewModel entity);
    }
}
#pragma warning restore 1591