#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 13:04:04
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using SampleCode.ViewModel;
using SampleCode.ViewModel.ListResult;
using SampleCode.ViewModel.SearchModel;
using System;
using System.Collections.Generic;
using SampleCode.Models;

namespace SampleCode.Interface
{
    public interface IUserManager : IManager
    {
        /// <summary>
        /// 檢查 Account 是否已經被使用
        /// </summary>
        /// <param name="account"></param>
        /// <returns></returns>
        bool AccountBeUse(string account);

        /// <summary>
        /// 變更密碼
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        bool ChangePassword(ChangePasswordViewModel viewModel);

        /// <summary>
        /// 建立 User
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(UserViewModel entity);

        /// <summary>
        /// 根據 id 刪除 User
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 檢查電子郵件是否存在
        /// </summary>
        /// <param name="email"></param>
        /// <returns></returns>
        bool EmailBeUse(string email);

        /// <summary>
        /// 取得忘記密碼 Token
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        string ForgotPassword(ForgotPasswordViewModel viewModel);

        /// <summary>
        /// 根據 id 取得 User
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        UserViewModel GetByID(Guid id);

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<UserListResult> Paging(UserSearchModel searchModel);

        /// <summary>
        /// 重置密碼
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        bool ResetPassword(ResetPasswordViewModel viewModel);

        /// <summary>
        /// 更新 User
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(UserViewModel entity);

        /// <summary>
        /// 登入驗證使用者
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        UserViewModel ValidateUser(ValidateUserViewModel viewModel);

        /// <summary>
        /// 驗證登入帳號，並回傳資訊
        /// </summary>
        /// <param name="viewModel"></param>
        /// <returns></returns>
        UserToken ValidateUserByApi(ValidateUserViewModel viewModel);

        /// <summary>
        /// 清除Token資料
        /// </summary>
        /// <param name="viewModel"></param>
        void ClearToken(UserViewModel viewModel);

        /// <summary>
        /// GetMarquees
        /// </summary>
        /// <returns></returns>
        List<string> GetMarquees();
    }
}
#pragma warning restore 1591