#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/01/2020 11:31:59
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using SampleCode.ViewModel;
using SampleCode.ViewModel.ListResult;
using SampleCode.ViewModel.SearchModel;

namespace SampleCode.Interface
{
    public interface IVisualMenuManager : IManager
    {
        /// <summary>
        /// 建立 VisualMenu
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Create(VisualMenuViewModel entity);

        /// <summary>
        /// 根據 id 刪除 VisualMenu
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        void Delete(List<Guid> id);

        /// <summary>
        /// 根據 id 取得 VisualMenu
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        VisualMenuViewModel GetByID(Guid id);

        /// <summary>
        /// 取得目前最大的順序序號
        /// </summary>
        /// <returns></returns>
        byte GetSequence();

        /// <summary>
        /// 分頁
        /// </summary>
        /// <param name="searchModel"></param>
        /// <returns></returns>
        Paging<VisualMenuListResult> Paging(VisualMenuSearchModel searchModel);

        /// <summary>
        /// 更新 VisualMenu
        /// </summary>
        /// <param name="entity"></param>
        /// <returns></returns>
        void Update(VisualMenuViewModel entity);
    }
}
#pragma warning restore 1591