#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 12:57:55
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace SampleCode.ViewModel.ListResult
{
    public class FunctionListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public string ModuleName { get; set; }
        public byte Sequence { get; set; }
        public byte GroupSequence { get; set; }
        public string Code { get; set; }
        public string GroupName { get; set; }
        public string SimpleName { get; set; }
        public string DisplayName { get; set; }
        public bool DisplayTree { get; set; }
        public bool DisplayHeader { get; set; }
        public bool IsEnable { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
    }
}
#pragma warning restore 1591