#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 12:57:55
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace SampleCode.ViewModel.ListResult
{
    public class ModuleListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public byte Sequence { get; set; }
        public string Name { get; set; }
        public bool IsEnable { get; set; }
        public bool MenuDisplay { get; set; }
    }
}
#pragma warning restore 1591