#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 06/23/2020 15:43:19
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace SampleCode.ViewModel.ListResult
{
    public class OperateRecordListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public string TableName { get; set; }
        public string RecordInfo { get; set; }
        public string Action { get; set; }
        public string Result { get; set; }
        public string OperateIP { get; set; }
        public string OperateUser { get; set; }
        public DateTime OperateTime { get; set; }
    }
}
#pragma warning restore 1591