#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/26/2019 09:33:34
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace SampleCode.ViewModel.ListResult
{
    public class SystemOptionListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public string Category { get; set; }
        public string OptionKey { get; set; }
        public string OptionValue { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateTime { get; set; }
    }
}
#pragma warning restore 1591