#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/25/2017 12:57:55
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace SampleCode.ViewModel.ListResult
{
    public class UserListResult
    {
        private string _photoPath;

        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public string Name { get; set; }
        public string Account { get; set; }
        public string Email { get; set; }
        public bool IsEnable { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateTime { get; set; }
        public DateTime LoginTime { get; set; }
        public string PhotoPath
        {
            get
            {
                return string.Format("<img src=\"{0}\" width=\"24\" onerror=\"this.src='/Content/images/none_photo.jpg';\"/>", _photoPath);
            }
            set
            {
                _photoPath = value;
            }
        }
        public string DefaultIndex { get; set; }
        public string Department { get; set; }
    }
}
#pragma warning restore 1591