#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 09/01/2020 11:32:25
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace SampleCode.ViewModel.ListResult
{
    public class VisualMenuListResult
    {
        public int SequenceNo { get; set; }
        public Guid ID { get; set; }
        public Nullable<Guid> ParentID { get; set; }
        public string ParentName { get; set; }
        public byte Sequence { get; set; }
        public byte MenuLevel { get; set; }
        public string MenuCode { get; set; }
        public string MenuName { get; set; }
        public string Layout { get; set; }
        public string IconPath { get; set; }
        public string HeaderPath { get; set; }
        public int ViewCount { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string Parameter { get; set; }
        public string ExternalUrl { get; set; }
        public bool IsInlinePage { get; set; }
        public bool IsShowFooter { get; set; }
        public bool IsEnable { get; set; }
        public string UpdateUser { get; set; }
        public DateTime UpdateTime { get; set; }
    }
}
#pragma warning restore 1591