//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceLibrary {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceLibrary.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 簡稱 的當地語系化字串。
        /// </summary>
        public static string Abbreviate {
            get {
                return ResourceManager.GetString("Abbreviate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限管理 的當地語系化字串。
        /// </summary>
        public static string AccessControl {
            get {
                return ResourceManager.GetString("AccessControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此帳號已經被鎖定！ 的當地語系化字串。
        /// </summary>
        public static string AccountLock {
            get {
                return ResourceManager.GetString("AccountLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳戶管理 的當地語系化字串。
        /// </summary>
        public static string AccountManagement {
            get {
                return ResourceManager.GetString("AccountManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AccProjID 的當地語系化字串。
        /// </summary>
        public static string AccProjID {
            get {
                return ResourceManager.GetString("AccProjID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 動作 的當地語系化字串。
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action Name 的當地語系化字串。
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增欄位 的當地語系化字串。
        /// </summary>
        public static string AddColumn {
            get {
                return ResourceManager.GetString("AddColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增檔案 的當地語系化字串。
        /// </summary>
        public static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增圖片 的當地語系化字串。
        /// </summary>
        public static string AddImage {
            get {
                return ResourceManager.GetString("AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AdditionalProjectID 的當地語系化字串。
        /// </summary>
        public static string AdditionalProjectID {
            get {
                return ResourceManager.GetString("AdditionalProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地址 的當地語系化字串。
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增影片 的當地語系化字串。
        /// </summary>
        public static string AddVideo {
            get {
                return ResourceManager.GetString("AddVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報名資料管理 的當地語系化字串。
        /// </summary>
        public static string ApplyManagement {
            get {
                return ResourceManager.GetString("ApplyManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限管理 的當地語系化字串。
        /// </summary>
        public static string AuthManagement {
            get {
                return ResourceManager.GetString("AuthManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待修正卡工作清單 的當地語系化字串。
        /// </summary>
        public static string BadProjectData {
            get {
                return ResourceManager.GetString("BadProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Banner 的當地語系化字串。
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 基本設定 的當地語系化字串。
        /// </summary>
        public static string BasicSetup {
            get {
                return ResourceManager.GetString("BasicSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Benefit 的當地語系化字串。
        /// </summary>
        public static string Benefit {
            get {
                return ResourceManager.GetString("Benefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 已被使用！ 的當地語系化字串。
        /// </summary>
        public static string BeUsedError {
            get {
                return ResourceManager.GetString("BeUsedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 位元碼 的當地語系化字串。
        /// </summary>
        public static string BitCode {
            get {
                return ResourceManager.GetString("BitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品牌 的當地語系化字串。
        /// </summary>
        public static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 品牌管理 的當地語系化字串。
        /// </summary>
        public static string BrandManagement {
            get {
                return ResourceManager.GetString("BrandManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 BrandName 的當地語系化字串。
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分類 的當地語系化字串。
        /// </summary>
        public static string BrandType {
            get {
                return ResourceManager.GetString("BrandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Budget 的當地語系化字串。
        /// </summary>
        public static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證碼 的當地語系化字串。
        /// </summary>
        public static string CaptchaCode {
            get {
                return ResourceManager.GetString("CaptchaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證編號 的當地語系化字串。
        /// </summary>
        public static string CaptchaID {
            get {
                return ResourceManager.GetString("CaptchaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卡友活動 的當地語系化字串。
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卡別內容管理 的當地語系化字串。
        /// </summary>
        public static string CardDetail {
            get {
                return ResourceManager.GetString("CardDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卡友專區 的當地語系化字串。
        /// </summary>
        public static string CardMemberZone {
            get {
                return ResourceManager.GetString("CardMemberZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卡片活動 的當地語系化字串。
        /// </summary>
        public static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卡別 的當地語系化字串。
        /// </summary>
        public static string CardType {
            get {
                return ResourceManager.GetString("CardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 卡別管理 的當地語系化字串。
        /// </summary>
        public static string CardTypeManagement {
            get {
                return ResourceManager.GetString("CardTypeManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 類別 的當地語系化字串。
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手機號碼 的當地語系化字串。
        /// </summary>
        public static string Cellphone {
            get {
                return ResourceManager.GetString("Cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變更密碼時間 的當地語系化字串。
        /// </summary>
        public static string ChangePassTime {
            get {
                return ResourceManager.GetString("ChangePassTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變更密碼 的當地語系化字串。
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變更密碼完成 的當地語系化字串。
        /// </summary>
        public static string ChangePasswordComplete {
            get {
                return ResourceManager.GetString("ChangePasswordComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變更密碼失敗 的當地語系化字串。
        /// </summary>
        public static string ChangePasswordFailed {
            get {
                return ResourceManager.GetString("ChangePasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變更後的密碼不可與前幾次相同 的當地語系化字串。
        /// </summary>
        public static string ChangePasswordSame {
            get {
                return ResourceManager.GetString("ChangePasswordSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IsChargeable 的當地語系化字串。
        /// </summary>
        public static string Chargeable {
            get {
                return ResourceManager.GetString("Chargeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 收費標準管理 的當地語系化字串。
        /// </summary>
        public static string ChargesInfo {
            get {
                return ResourceManager.GetString("ChargesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢查 {0} {1} 是否重複發生錯誤！ 的當地語系化字串。
        /// </summary>
        public static string CheckBeUsedError {
            get {
                return ResourceManager.GetString("CheckBeUsedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選取項 的當地語系化字串。
        /// </summary>
        public static string Checkbox {
            get {
                return ResourceManager.GetString("Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變更密碼錯誤 的當地語系化字串。
        /// </summary>
        public static string CheckPasswordError {
            get {
                return ResourceManager.GetString("CheckPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 類別 的當地語系化字串。
        /// </summary>
        public static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分類 的當地語系化字串。
        /// </summary>
        public static string Classify {
            get {
                return ResourceManager.GetString("Classify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ClientName 的當地語系化字串。
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關閉 的當地語系化字串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 代碼 的當地語系化字串。
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Commission 的當地語系化字串。
        /// </summary>
        public static string Commission {
            get {
                return ResourceManager.GetString("Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司/品牌 的當地語系化字串。
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CompareDate 的當地語系化字串。
        /// </summary>
        public static string CompareDate {
            get {
                return ResourceManager.GetString("CompareDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CompareEngName 的當地語系化字串。
        /// </summary>
        public static string CompareEngName {
            get {
                return ResourceManager.GetString("CompareEngName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 與 {0} 不相符！ 的當地語系化字串。
        /// </summary>
        public static string CompareError {
            get {
                return ResourceManager.GetString("CompareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CompareLocName 的當地語系化字串。
        /// </summary>
        public static string CompareLocName {
            get {
                return ResourceManager.GetString("CompareLocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CompareUniqNo 的當地語系化字串。
        /// </summary>
        public static string CompareUniqNo {
            get {
                return ResourceManager.GetString("CompareUniqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CompleteDate 的當地語系化字串。
        /// </summary>
        public static string CompleteDate {
            get {
                return ResourceManager.GetString("CompleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司名 的當地語系化字串。
        /// </summary>
        public static string CompName {
            get {
                return ResourceManager.GetString("CompName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組態索引 的當地語系化字串。
        /// </summary>
        public static string ConfigKey {
            get {
                return ResourceManager.GetString("ConfigKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組態值 的當地語系化字串。
        /// </summary>
        public static string ConfigValue {
            get {
                return ResourceManager.GetString("ConfigValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認密碼 的當地語系化字串。
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡方式 的當地語系化字串。
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 傳真號碼 的當地語系化字串。
        /// </summary>
        public static string ContactFax {
            get {
                return ResourceManager.GetString("ContactFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 聯絡人 的當地語系化字串。
        /// </summary>
        public static string ContactPerson {
            get {
                return ResourceManager.GetString("ContactPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話號碼 的當地語系化字串。
        /// </summary>
        public static string ContactTel {
            get {
                return ResourceManager.GetString("ContactTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 內容 的當地語系化字串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 控制器 的當地語系化字串。
        /// </summary>
        public static string Controller {
            get {
                return ResourceManager.GetString("Controller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Controller Name 的當地語系化字串。
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複製 的當地語系化字串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 Non-Chargeable 專案 的當地語系化字串。
        /// </summary>
        public static string CreateNonCharge {
            get {
                return ResourceManager.GetString("CreateNonCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立時間 的當地語系化字串。
        /// </summary>
        public static string CreateTime {
            get {
                return ResourceManager.GetString("CreateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立者 的當地語系化字串。
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CRMSourSys 的當地語系化字串。
        /// </summary>
        public static string CRMSourSys {
            get {
                return ResourceManager.GetString("CRMSourSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CRMURNID 的當地語系化字串。
        /// </summary>
        public static string CRMURNID {
            get {
                return ResourceManager.GetString("CRMURNID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CurrencyINR 的當地語系化字串。
        /// </summary>
        public static string CurrencyINR {
            get {
                return ResourceManager.GetString("CurrencyINR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 客戶名稱 的當地語系化字串。
        /// </summary>
        public static string CUST_ABBR {
            get {
                return ResourceManager.GetString("CUST_ABBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Workfront匯入 的當地語系化字串。
        /// </summary>
        public static string DataImport {
            get {
                return ResourceManager.GetString("DataImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 從 CaratStation 匯入 的當地語系化字串。
        /// </summary>
        public static string DataMaintain {
            get {
                return ResourceManager.GetString("DataMaintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料型態 的當地語系化字串。
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 0數值/1文字 的當地語系化字串。
        /// </summary>
        public static string DataTypeDescription {
            get {
                return ResourceManager.GetString("DataTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日期(起)不可大於日期(迄) 的當地語系化字串。
        /// </summary>
        public static string DateFormatError {
            get {
                return ResourceManager.GetString("DateFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設首頁 的當地語系化字串。
        /// </summary>
        public static string DefaultIndex {
            get {
                return ResourceManager.GetString("DefaultIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 部門 的當地語系化字串。
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 部門主管 的當地語系化字串。
        /// </summary>
        public static string DepartmentHead {
            get {
                return ResourceManager.GetString("DepartmentHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 部門層級 的當地語系化字串。
        /// </summary>
        public static string DepartmentLevel {
            get {
                return ResourceManager.GetString("DepartmentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 部門管理 的當地語系化字串。
        /// </summary>
        public static string DepartmentManagement {
            get {
                return ResourceManager.GetString("DepartmentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上級部門 的當地語系化字串。
        /// </summary>
        public static string DepartmentParent {
            get {
                return ResourceManager.GetString("DepartmentParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相依功能 的當地語系化字串。
        /// </summary>
        public static string Dependency {
            get {
                return ResourceManager.GetString("Dependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影片說明 的當地語系化字串。
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Description 的當地語系化字串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 詳細資料 的當地語系化字串。
        /// </summary>
        public static string DetailInfo {
            get {
                return ResourceManager.GetString("DetailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檢視 的當地語系化字串。
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示於標頭 的當地語系化字串。
        /// </summary>
        public static string DisplayHeader {
            get {
                return ResourceManager.GetString("DisplayHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示名稱 的當地語系化字串。
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示於樹狀選單 的當地語系化字串。
        /// </summary>
        public static string DisplayTree {
            get {
                return ResourceManager.GetString("DisplayTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載 的當地語系化字串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子信箱 的當地語系化字串。
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 e-Mail 格式錯誤！ 的當地語系化字串。
        /// </summary>
        public static string EmailError {
            get {
                return ResourceManager.GetString("EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 e-Mail 不存在！ 的當地語系化字串。
        /// </summary>
        public static string EmailNotFoundError {
            get {
                return ResourceManager.GetString("EmailNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 留白表示不變更密碼 的當地語系化字串。
        /// </summary>
        public static string EmptyIsNotChangePassword {
            get {
                return ResourceManager.GetString("EmptyIsNotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 活動報名 的當地語系化字串。
        /// </summary>
        public static string EventReg {
            get {
                return ResourceManager.GetString("EventReg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行 {0} {1} 完成！ 的當地語系化字串。
        /// </summary>
        public static string ExecutionCompleted {
            get {
                return ResourceManager.GetString("ExecutionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認要 {0} 所選的 {1} 嗎？ 的當地語系化字串。
        /// </summary>
        public static string ExecutionConfirm {
            get {
                return ResourceManager.GetString("ExecutionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行 {0} {1} 失敗！ 的當地語系化字串。
        /// </summary>
        public static string ExecutionFailed {
            get {
                return ResourceManager.GetString("ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行 {0} {1} ID = {2} 失敗！ 的當地語系化字串。
        /// </summary>
        public static string ExecutionFailedWithID {
            get {
                return ResourceManager.GetString("ExecutionFailedWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離開 的當地語系化字串。
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出CSV 的當地語系化字串。
        /// </summary>
        public static string ExportCSV {
            get {
                return ResourceManager.GetString("ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 否 的當地語系化字串。
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 欄位 的當地語系化字串。
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 欄位名稱 的當地語系化字串。
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FinSourSys 的當地語系化字串。
        /// </summary>
        public static string FinSourSys {
            get {
                return ResourceManager.GetString("FinSourSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 忘記密碼 的當地語系化字串。
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 [div][p]先生/小姐 您好：[/p][p]您要重置 {0} 密碼，請點擊連結繼續完成後續步驟，連結如下：[/p][p][a href=&apos;{1}&apos;]啟用連結[/a][/p][p]請點擊連結進行啟用！[/p][/div] 的當地語系化字串。
        /// </summary>
        public static string ForgotPasswordMailBody {
            get {
                return ResourceManager.GetString("ForgotPasswordMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重置您的 {0} 密碼。 的當地語系化字串。
        /// </summary>
        public static string ForgotPasswordMailSubject {
            get {
                return ResourceManager.GetString("ForgotPasswordMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重置密碼信件已經發送至您的信箱帳號，請收取信件並完成後續動作。 的當地語系化字串。
        /// </summary>
        public static string ForgotPasswordProcessCompleted {
            get {
                return ResourceManager.GetString("ForgotPasswordProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重置密碼失敗！ 的當地語系化字串。
        /// </summary>
        public static string ForgotPasswordProcessFailed {
            get {
                return ResourceManager.GetString("ForgotPasswordProcessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 格式 的當地語系化字串。
        /// </summary>
        public static string Formatter {
            get {
                return ResourceManager.GetString("Formatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自由欄位 的當地語系化字串。
        /// </summary>
        public static string FreeFields {
            get {
                return ResourceManager.GetString("FreeFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自由欄位設定 的當地語系化字串。
        /// </summary>
        public static string FreeFieldSetting {
            get {
                return ResourceManager.GetString("FreeFieldSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自由欄位管理 的當地語系化字串。
        /// </summary>
        public static string FreeFieldSettingManagement {
            get {
                return ResourceManager.GetString("FreeFieldSettingManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能 的當地語系化字串。
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能 的當地語系化字串。
        /// </summary>
        public static string Functions {
            get {
                return ResourceManager.GetString("Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產出 的當地語系化字串。
        /// </summary>
        public static string GenerateURL {
            get {
                return ResourceManager.GetString("GenerateURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得檢視 {0} 資料 ID = {1} 發生錯誤！ 的當地語系化字串。
        /// </summary>
        public static string GetDetailsDataError {
            get {
                return ResourceManager.GetString("GetDetailsDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得編輯 {0} 資料 ID = {1} 發生錯誤！ 的當地語系化字串。
        /// </summary>
        public static string GetEditDataError {
            get {
                return ResourceManager.GetString("GetEditDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 GroupName 的當地語系化字串。
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群組順序 的當地語系化字串。
        /// </summary>
        public static string GroupSequence {
            get {
                return ResourceManager.GetString("GroupSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立標籤 的當地語系化字串。
        /// </summary>
        public static string Hash {
            get {
                return ResourceManager.GetString("Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Hash Token 的當地語系化字串。
        /// </summary>
        public static string HashToken {
            get {
                return ResourceManager.GetString("HashToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已經有帳號了? 的當地語系化字串。
        /// </summary>
        public static string HaveAccount {
            get {
                return ResourceManager.GetString("HaveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 版型路徑 的當地語系化字串。
        /// </summary>
        public static string HeaderPath {
            get {
                return ResourceManager.GetString("HeaderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全區圖 的當地語系化字串。
        /// </summary>
        public static string HoleAreaPic {
            get {
                return ResourceManager.GetString("HoleAreaPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁管理 的當地語系化字串。
        /// </summary>
        public static string HomeManager {
            get {
                return ResourceManager.GetString("HomeManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖示路徑 的當地語系化字串。
        /// </summary>
        public static string IconPath {
            get {
                return ResourceManager.GetString("IconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IG 的當地語系化字串。
        /// </summary>
        public static string IG {
            get {
                return ResourceManager.GetString("IG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影像替代文字 的當地語系化字串。
        /// </summary>
        public static string ImageAlt {
            get {
                return ResourceManager.GetString("ImageAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影像高度 的當地語系化字串。
        /// </summary>
        public static string ImageHeight {
            get {
                return ResourceManager.GetString("ImageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影像路徑 的當地語系化字串。
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影像寬度 的當地語系化字串。
        /// </summary>
        public static string ImageWidth {
            get {
                return ResourceManager.GetString("ImageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ImportDate 的當地語系化字串。
        /// </summary>
        public static string ImportDate {
            get {
                return ResourceManager.GetString("ImportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ImportEngName 的當地語系化字串。
        /// </summary>
        public static string ImportEngName {
            get {
                return ResourceManager.GetString("ImportEngName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入檔案 的當地語系化字串。
        /// </summary>
        public static string ImportFile {
            get {
                return ResourceManager.GetString("ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ImportLocName 的當地語系化字串。
        /// </summary>
        public static string ImportLocName {
            get {
                return ResourceManager.GetString("ImportLocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇從CaratStation匯入的時間點 的當地語系化字串。
        /// </summary>
        public static string ImportStart {
            get {
                return ResourceManager.GetString("ImportStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入時間 的當地語系化字串。
        /// </summary>
        public static string ImportTime {
            get {
                return ResourceManager.GetString("ImportTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ImportType 的當地語系化字串。
        /// </summary>
        public static string ImportType {
            get {
                return ResourceManager.GetString("ImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ImportUniqNo 的當地語系化字串。
        /// </summary>
        public static string ImportUniqNo {
            get {
                return ResourceManager.GetString("ImportUniqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簡介 的當地語系化字串。
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相關資訊管理 的當地語系化字串。
        /// </summary>
        public static string InfoManagement {
            get {
                return ResourceManager.GetString("InfoManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否有附檔 0 :無  1:有 的當地語系化字串。
        /// </summary>
        public static string IsAttached {
            get {
                return ResourceManager.GetString("IsAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否收費 的當地語系化字串。
        /// </summary>
        public static string IsChargeable {
            get {
                return ResourceManager.GetString("IsChargeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用 的當地語系化字串。
        /// </summary>
        public static string IsEnable {
            get {
                return ResourceManager.GetString("IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁是否顯示 的當地語系化字串。
        /// </summary>
        public static string IsHomePage {
            get {
                return ResourceManager.GetString("IsHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 嵌入式頁面 的當地語系化字串。
        /// </summary>
        public static string IsInlinePage {
            get {
                return ResourceManager.GetString("IsInlinePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主機構 的當地語系化字串。
        /// </summary>
        public static string IsMajor {
            get {
                return ResourceManager.GetString("IsMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示於頁尾 的當地語系化字串。
        /// </summary>
        public static string IsShowFooter {
            get {
                return ResourceManager.GetString("IsShowFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職缺類別 的當地語系化字串。
        /// </summary>
        public static string JobClass {
            get {
                return ResourceManager.GetString("JobClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇職缺類別 的當地語系化字串。
        /// </summary>
        public static string JobClassList {
            get {
                return ResourceManager.GetString("JobClassList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職缺 的當地語系化字串。
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關鍵字 的當地語系化字串。
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後登入時間 的當地語系化字串。
        /// </summary>
        public static string LastLoginTime {
            get {
                return ResourceManager.GetString("LastLoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 版型 的當地語系化字串。
        /// </summary>
        public static string Layout {
            get {
                return ResourceManager.GetString("Layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LegalEntity 的當地語系化字串。
        /// </summary>
        public static string LegalEntity {
            get {
                return ResourceManager.GetString("LegalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LineofBusiness 的當地語系化字串。
        /// </summary>
        public static string LineofBusiness {
            get {
                return ResourceManager.GetString("LineofBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列表選項 的當地語系化字串。
        /// </summary>
        public static string ListOption {
            get {
                return ResourceManager.GetString("ListOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 地點 的當地語系化字串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入失敗！帳號或密碼有誤！ 的當地語系化字串。
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入時間 的當地語系化字串。
        /// </summary>
        public static string LoginTime {
            get {
                return ResourceManager.GetString("LoginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子信箱 的當地語系化字串。
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Market 的當地語系化字串。
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 媒體別 的當地語系化字串。
        /// </summary>
        public static string MEDIA_KIND_NAME {
            get {
                return ResourceManager.GetString("MEDIA_KIND_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MediaType 的當地語系化字串。
        /// </summary>
        public static string MediaType {
            get {
                return ResourceManager.GetString("MediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能編號 的當地語系化字串。
        /// </summary>
        public static string MenuCode {
            get {
                return ResourceManager.GetString("MenuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示於選單 的當地語系化字串。
        /// </summary>
        public static string MenuDisplay {
            get {
                return ResourceManager.GetString("MenuDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能表圖示 的當地語系化字串。
        /// </summary>
        public static string MenuIcon {
            get {
                return ResourceManager.GetString("MenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能層級 的當地語系化字串。
        /// </summary>
        public static string MenuLevel {
            get {
                return ResourceManager.GetString("MenuLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        public static string MenuName {
            get {
                return ResourceManager.GetString("MenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上層功能 的當地語系化字串。
        /// </summary>
        public static string MenuParent {
            get {
                return ResourceManager.GetString("MenuParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分鐘 的當地語系化字串。
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 模組 的當地語系化字串。
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名稱 的當地語系化字串。
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼 的當地語系化字串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無 {0} ID = {1} 的資料！ 的當地語系化字串。
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案讀取錯誤 的當地語系化字串。
        /// </summary>
        public static string NoFile {
            get {
                return ResourceManager.GetString("NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 非收費項目 的當地語系化字串。
        /// </summary>
        public static string NonChargeable {
            get {
                return ResourceManager.GetString("NonChargeable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Non-Chargeable管理 的當地語系化字串。
        /// </summary>
        public static string NonChargeableManagement {
            get {
                return ResourceManager.GetString("NonChargeableManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 人數 的當地語系化字串。
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數值類型 的當地語系化字串。
        /// </summary>
        public static string Numerical {
            get {
                return ResourceManager.GetString("Numerical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Office 的當地語系化字串。
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 舊密碼 的當地語系化字串。
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作IP位址 的當地語系化字串。
        /// </summary>
        public static string OperateIP {
            get {
                return ResourceManager.GetString("OperateIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作記錄 的當地語系化字串。
        /// </summary>
        public static string OperateRecord {
            get {
                return ResourceManager.GetString("OperateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作記錄管理 的當地語系化字串。
        /// </summary>
        public static string OperateRecordManagement {
            get {
                return ResourceManager.GetString("OperateRecordManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作時間 的當地語系化字串。
        /// </summary>
        public static string OperateTime {
            get {
                return ResourceManager.GetString("OperateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作者 的當地語系化字串。
        /// </summary>
        public static string OperateUser {
            get {
                return ResourceManager.GetString("OperateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選項 的當地語系化字串。
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選項索引 的當地語系化字串。
        /// </summary>
        public static string OptionKey {
            get {
                return ResourceManager.GetString("OptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選項值 的當地語系化字串。
        /// </summary>
        public static string OptionValue {
            get {
                return ResourceManager.GetString("OptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TSM 的當地語系化字串。
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OtherSource 的當地語系化字串。
        /// </summary>
        public static string OtherSource {
            get {
                return ResourceManager.GetString("OtherSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 專案負責人 的當地語系化字串。
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OwnerEmail 的當地語系化字串。
        /// </summary>
        public static string OwnerEmail {
            get {
                return ResourceManager.GetString("OwnerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 分頁錯誤！ 的當地語系化字串。
        /// </summary>
        public static string PagingError {
            get {
                return ResourceManager.GetString("PagingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 參數錯誤！ 的當地語系化字串。
        /// </summary>
        public static string ParamError {
            get {
                return ResourceManager.GetString("ParamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數 的當地語系化字串。
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停車資訊 的當地語系化字串。
        /// </summary>
        public static string ParkingInfo {
            get {
                return ResourceManager.GetString("ParkingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼長度必須8~12個字元（必須同時包含大寫字母、小寫字母、特殊符號及數字） 的當地語系化字串。
        /// </summary>
        public static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限不足，請更換登入帳號！或是連線已經逾時！ 的當地語系化字串。
        /// </summary>
        public static string PermissionsDenied {
            get {
                return ResourceManager.GetString("PermissionsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相片 的當地語系化字串。
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 相片路徑 的當地語系化字串。
        /// </summary>
        public static string PhotoPath {
            get {
                return ResourceManager.GetString("PhotoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 圖片名稱 的當地語系化字串。
        /// </summary>
        public static string PicName {
            get {
                return ResourceManager.GetString("PicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入帳號 的當地語系化字串。
        /// </summary>
        public static string PlaceHolderForAccount {
            get {
                return ResourceManager.GetString("PlaceHolderForAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入驗證碼 的當地語系化字串。
        /// </summary>
        public static string PlaceHolderForCaptchaCode {
            get {
                return ResourceManager.GetString("PlaceHolderForCaptchaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請確認新密碼 的當地語系化字串。
        /// </summary>
        public static string PlaceHolderForConfirmPassword {
            get {
                return ResourceManager.GetString("PlaceHolderForConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入您註冊的信箱 的當地語系化字串。
        /// </summary>
        public static string PlaceHolderForEmail {
            get {
                return ResourceManager.GetString("PlaceHolderForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入新密碼 的當地語系化字串。
        /// </summary>
        public static string PlaceHolderForNewPassword {
            get {
                return ResourceManager.GetString("PlaceHolderForNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入密碼 的當地語系化字串。
        /// </summary>
        public static string PlaceHolderForPassword {
            get {
                return ResourceManager.GetString("PlaceHolderForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇 {0} ... 的當地語系化字串。
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PortfolioName 的當地語系化字串。
        /// </summary>
        public static string PortfolioName {
            get {
                return ResourceManager.GetString("PortfolioName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PortfolioOwnerID 的當地語系化字串。
        /// </summary>
        public static string PortfolioOwnerID {
            get {
                return ResourceManager.GetString("PortfolioOwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 前言 的當地語系化字串。
        /// </summary>
        public static string Preface {
            get {
                return ResourceManager.GetString("Preface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隱私權保護政策 的當地語系化字串。
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品名稱 的當地語系化字串。
        /// </summary>
        public static string PROD_NAME {
            get {
                return ResourceManager.GetString("PROD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ProgramName 的當地語系化字串。
        /// </summary>
        public static string ProgramName {
            get {
                return ResourceManager.GetString("ProgramName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ProgramOwnerID 的當地語系化字串。
        /// </summary>
        public static string ProgramOwnerID {
            get {
                return ResourceManager.GetString("ProgramOwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ProjectData 的當地語系化字串。
        /// </summary>
        public static string ProjectData {
            get {
                return ResourceManager.GetString("ProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢、匯入 的當地語系化字串。
        /// </summary>
        public static string ProjectDataManagement {
            get {
                return ResourceManager.GetString("ProjectDataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ProjectID 的當地語系化字串。
        /// </summary>
        public static string ProjectID {
            get {
                return ResourceManager.GetString("ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ProjectName 的當地語系化字串。
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ProjectOwnerID 的當地語系化字串。
        /// </summary>
        public static string ProjectOwnerID {
            get {
                return ResourceManager.GetString("ProjectOwnerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ProjectStatus 的當地語系化字串。
        /// </summary>
        public static string ProjectStatus {
            get {
                return ResourceManager.GetString("ProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 專案型態 的當地語系化字串。
        /// </summary>
        public static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發佈人 的當地語系化字串。
        /// </summary>
        public static string PublishUser {
            get {
                return ResourceManager.GetString("PublishUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數值應介於 {0} 至 {1} 之間！ 的當地語系化字串。
        /// </summary>
        public static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作記錄 的當地語系化字串。
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作內容 的當地語系化字串。
        /// </summary>
        public static string RecordInfo {
            get {
                return ResourceManager.GetString("RecordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 RecordStatus 的當地語系化字串。
        /// </summary>
        public static string RecordStatus {
            get {
                return ResourceManager.GetString("RecordStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報名日期 的當地語系化字串。
        /// </summary>
        public static string RegDate {
            get {
                return ResourceManager.GetString("RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Region 的當地語系化字串。
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重新匯入 的當地語系化字串。
        /// </summary>
        public static string ReImport {
            get {
                return ResourceManager.GetString("ReImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 欄位必須填寫！ 的當地語系化字串。
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重置 的當地語系化字串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重置密碼 的當地語系化字串。
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重置密碼完成。 的當地語系化字串。
        /// </summary>
        public static string ResetPasswordProcessCompleted {
            get {
                return ResourceManager.GetString("ResetPasswordProcessCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結果 的當地語系化字串。
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身份 的當地語系化字串。
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色管理 的當地語系化字串。
        /// </summary>
        public static string RoleManagement {
            get {
                return ResourceManager.GetString("RoleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存 的當地語系化字串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存資料失敗 的當地語系化字串。
        /// </summary>
        public static string SaveDataError {
            get {
                return ResourceManager.GetString("SaveDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存資料成功 的當地語系化字串。
        /// </summary>
        public static string SaveDataSuccess {
            get {
                return ResourceManager.GetString("SaveDataSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 秒後登出，關閉此視窗後繼續操作。 的當地語系化字串。
        /// </summary>
        public static string SecondsLogout {
            get {
                return ResourceManager.GetString("SecondsLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 依更新時間選取樓層地圖 的當地語系化字串。
        /// </summary>
        public static string SelectFloorMap {
            get {
                return ResourceManager.GetString("SelectFloorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 順序 的當地語系化字串。
        /// </summary>
        public static string Sequence {
            get {
                return ResourceManager.GetString("Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 序號 的當地語系化字串。
        /// </summary>
        public static string SequenceNo {
            get {
                return ResourceManager.GetString("SequenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 貼心服務管理 的當地語系化字串。
        /// </summary>
        public static string ServiceManagement {
            get {
                return ResourceManager.GetString("ServiceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 場次 的當地語系化字串。
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示日期 的當地語系化字串。
        /// </summary>
        public static string ShowDate {
            get {
                return ResourceManager.GetString("ShowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示文字 的當地語系化字串。
        /// </summary>
        public static string ShowText {
            get {
                return ResourceManager.GetString("ShowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示方式 的當地語系化字串。
        /// </summary>
        public static string ShowType {
            get {
                return ResourceManager.GetString("ShowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入 的當地語系化字串。
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簡稱 的當地語系化字串。
        /// </summary>
        public static string SimpleName {
            get {
                return ResourceManager.GetString("SimpleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 可排序 的當地語系化字串。
        /// </summary>
        public static string Sortable {
            get {
                return ResourceManager.GetString("Sortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分類 的當地語系化字串。
        /// </summary>
        public static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 StartDate 的當地語系化字串。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否啟用 的當地語系化字串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束時間不可小於開始時間 的當地語系化字串。
        /// </summary>
        public static string StopGreaterThanStart {
            get {
                return ResourceManager.GetString("StopGreaterThanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請勿輸入超過 {1} 個字！ 的當地語系化字串。
        /// </summary>
        public static string StringLengthError {
            get {
                return ResourceManager.GetString("StringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文字類型 的當地語系化字串。
        /// </summary>
        public static string Strings {
            get {
                return ResourceManager.GetString("Strings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 送出 的當地語系化字串。
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統組態 的當地語系化字串。
        /// </summary>
        public static string SystemConfig {
            get {
                return ResourceManager.GetString("SystemConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統組態管理 的當地語系化字串。
        /// </summary>
        public static string SystemConfigManagement {
            get {
                return ResourceManager.GetString("SystemConfigManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統發生錯誤！ 的當地語系化字串。
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統功能 的當地語系化字串。
        /// </summary>
        public static string SystemFunction {
            get {
                return ResourceManager.GetString("SystemFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理系統 的當地語系化字串。
        /// </summary>
        public static string SystemMessage {
            get {
                return ResourceManager.GetString("SystemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統模組 的當地語系化字串。
        /// </summary>
        public static string SystemModule {
            get {
                return ResourceManager.GetString("SystemModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sample System Name 的當地語系化字串。
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統選項 的當地語系化字串。
        /// </summary>
        public static string SystemOption {
            get {
                return ResourceManager.GetString("SystemOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統選項管理 的當地語系化字串。
        /// </summary>
        public static string SystemOptionManagement {
            get {
                return ResourceManager.GetString("SystemOptionManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料表名稱 的當地語系化字串。
        /// </summary>
        public static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 標籤 的當地語系化字串。
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話 的當地語系化字串。
        /// </summary>
        public static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文字 的當地語系化字串。
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單元 的當地語系化字串。
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改時間 的當地語系化字串。
        /// </summary>
        public static string UpdateTime {
            get {
                return ResourceManager.GetString("UpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改者 的當地語系化字串。
        /// </summary>
        public static string UpdateUser {
            get {
                return ResourceManager.GetString("UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳大圖片 的當地語系化字串。
        /// </summary>
        public static string UploadBigPic {
            get {
                return ResourceManager.GetString("UploadBigPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UploadDate 的當地語系化字串。
        /// </summary>
        public static string UploadDate {
            get {
                return ResourceManager.GetString("UploadDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UploadEngName 的當地語系化字串。
        /// </summary>
        public static string UploadEngName {
            get {
                return ResourceManager.GetString("UploadEngName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳檔案 的當地語系化字串。
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳封面 的當地語系化字串。
        /// </summary>
        public static string UploadFront {
            get {
                return ResourceManager.GetString("UploadFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳版型 的當地語系化字串。
        /// </summary>
        public static string UploadHeader {
            get {
                return ResourceManager.GetString("UploadHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳圖示 的當地語系化字串。
        /// </summary>
        public static string UploadIcon {
            get {
                return ResourceManager.GetString("UploadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳影像 的當地語系化字串。
        /// </summary>
        public static string UploadImage {
            get {
                return ResourceManager.GetString("UploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UploadLocName 的當地語系化字串。
        /// </summary>
        public static string UploadLocName {
            get {
                return ResourceManager.GetString("UploadLocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳照片 的當地語系化字串。
        /// </summary>
        public static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳圖片 的當地語系化字串。
        /// </summary>
        public static string UploadPic {
            get {
                return ResourceManager.GetString("UploadPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上傳小圖片 的當地語系化字串。
        /// </summary>
        public static string UploadSmallPic {
            get {
                return ResourceManager.GetString("UploadSmallPic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 UploadUniqNo 的當地語系化字串。
        /// </summary>
        public static string UploadUniqNo {
            get {
                return ResourceManager.GetString("UploadUniqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (上傳Zip檔) 的當地語系化字串。
        /// </summary>
        public static string UploadZip {
            get {
                return ResourceManager.GetString("UploadZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連結網址 的當地語系化字串。
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連結名稱 的當地語系化字串。
        /// </summary>
        public static string URLName {
            get {
                return ResourceManager.GetString("URLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者參數 的當地語系化字串。
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者參數管理 的當地語系化字串。
        /// </summary>
        public static string UserProfileManagement {
            get {
                return ResourceManager.GetString("UserProfileManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用期限 的當地語系化字串。
        /// </summary>
        public static string UseStartDate {
            get {
                return ResourceManager.GetString("UseStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 瀏覽人數 的當地語系化字串。
        /// </summary>
        public static string ViewCount {
            get {
                return ResourceManager.GetString("ViewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 可顯示 的當地語系化字串。
        /// </summary>
        public static string Visible {
            get {
                return ResourceManager.GetString("Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 視覺功能表 的當地語系化字串。
        /// </summary>
        public static string VisualMenu {
            get {
                return ResourceManager.GetString("VisualMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 視覺功能表管理 的當地語系化字串。
        /// </summary>
        public static string VisualMenuManagement {
            get {
                return ResourceManager.GetString("VisualMenuManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備取人數 的當地語系化字串。
        /// </summary>
        public static string WaitingNum {
            get {
                return ResourceManager.GetString("WaitingNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網址 的當地語系化字串。
        /// </summary>
        public static string WebSiteUrl {
            get {
                return ResourceManager.GetString("WebSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作卡號 的當地語系化字串。
        /// </summary>
        public static string WORK_CARD_NO {
            get {
                return ResourceManager.GetString("WORK_CARD_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WorkfrontImport 的當地語系化字串。
        /// </summary>
        public static string WorkfrontImport {
            get {
                return ResourceManager.GetString("WorkfrontImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯入、查詢 的當地語系化字串。
        /// </summary>
        public static string WorkfrontReport {
            get {
                return ResourceManager.GetString("WorkfrontReport", resourceCulture);
            }
        }
    }
}
