#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Generated at 10/13/2017 15:10:00
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleCode.ViewModel.SearchModel
{
    public class RoleSearchModel : EnableSearchModel
    {
    }
}
#pragma warning restore 1591